version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: cntrlflow_postgres
    environment:
      POSTGRES_DB: cntrlflowdb
      POSTGRES_USER: cntrlflow
      POSTGRES_PASSWORD: cntrlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
